# Generated by Django 4.1.4 on 2022-12-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image2',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.AddField(
            model_name='post',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
