# Generated by Django 4.1.4 on 2022-12-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_image2_post_video_remove_post_image3_post_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='doc',
            new_name='docx',
        ),
    ]
